APPLY_FIXES: all
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

PRE_COMMANDS:
  - command: cat /etc/os-release
  - command: pip install -e .
    venv: pylint

PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT

REPOSITORY_CHECKOV_ARGUMENTS: --skip-check CKV_GHA_7

DISABLE_LINTERS:
  - SPELL_CSPELL
  - COPYPASTE_JSCPD
  - PYTHON_FLAKE8
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - JSON_JSONLINT
  - MAKEFILE_CHECKMAKE
  - SPELL_LYCHEE
  - REPOSITORY_GRYPE
