APPLY_FIXES: all

PRE_COMMANDS:
  - command: cat /etc/os-release
  - command: pip install numpy
    venv: pylint

PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT

DISABLE_LINTERS:
  - SPELL_CSPELL
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - JSON_JSONLINT
  - MAKEFILE_CHECKMAKE
  - SPELL_LYCHEE
  - REPOSITORY_GRYPE
